'use client';

import { useEffect, useState } from "react";
import DarkTheme from "@/components/DarkTheme";
import "./globals.css";

// export const metadata = {
//   title: "Tailwind",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isDarkMode, setIsDarkMode] = useState(false);

  useEffect(() => {
    // Apply dark mode class on initial render based on the state
    if (isDarkMode) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  }, [isDarkMode]);

  return (
    <html lang="en" className={isDarkMode ? "dark" : ""}>
      <body>
        <DarkTheme isDarkMode={isDarkMode} setIsDarkMode={setIsDarkMode} />
        {children}
      </body>
    </html>
  );
}
